service: lambdas

frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.8

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  get_joke:
    handler: handler.get_joke
    events:
      - http:
          path: joke
          method: get


plugins:
  - serverless-python-requirements
